name: gis2
channels:
#- pytorch
- anaconda
- conda-forge
dependencies:
- python=3.6
- numpy
#- gdal
- rasterio
- rasterstats
#- tensorflow-gpu
- pip:
    - ipdb
    - argparse
    - matplotlib
    - opencv-python
    - keras
    - sklearn
    - pandas
    - scikit-image
    - requests
    - tqdm
    - xlrd
    - Shapely
    - fiona
    #- rasterio must be installed with conda, conda install -c conda-forge rasterio
    - utm
    - retrying
    - pyproj
    - google-cloud-storage
    - geopandas
    - geojson
    - seaborn
#    - jupyter-notebook
