data_dir: '../data'
chirps_dir: '/Volumes/sel_external/chirps'
tmp_dir:  '../data/chirps/tmp'
elec_results_dir: '../results'

irrigibility_lb: 85 # percent
frac_irrig: 0.1 # percent of land above irrigibility_lb to be irrigated
gw_depth: 20 # meters
w2w_eff: 0.5 # wire to water efficiency
h20_req: 6 #mm/day

year: 2018

rescale_reprojected: True

